services:
  auth-center:
    extends:
      file: docker-compose.microservices.yml
      service: auth-center

networks:
  control:
    name: ${CONTROL_NETWORK_NAME:-x-sentinel-control}
    external: ${CONTROL_NETWORK_EXTERNAL:-true}
