services:
  monitor-center:
    extends:
      file: docker-compose.microservices.yml
      service: monitor-center

networks:
  control:
    name: ${CONTROL_NETWORK_NAME:-x-sentinel-control}
    external: ${CONTROL_NETWORK_EXTERNAL:-true}
