<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { DeleteOutlined, EditOutlined, HistoryOutlined, PlusOutlined, SendOutlined, UploadOutlined } from '@ant-design/icons-vue'
import { message, Modal } from 'ant-design-vue'
import { articlesApi, qqApi } from '@/services/api'
import { getErrorMessage } from '@/services/http'
import type { Article, ArticlePayload, QQBotAccount, QQJoinedGroup } from '@/types'
import { formatDateTime } from '@/utils/format'
import PageHeader from '@/components/PageHeader.vue'
import StatusPill from '@/components/StatusPill.vue'
const rows = ref<Article[]>([]); const total = ref(0); const loading = ref(false); const saving = ref(false); const uploading = ref(false)
const open = ref(false); const publishOpen = ref(false); const historyOpen = ref(false); const editing = ref<Article | null>(null); const publishing = ref<Article | null>(null)
const bots = ref<QQBotAccount[]>([]); const groups = ref<QQJoinedGroup[]>([]); const history = ref<any[]>([])
const form = reactive<ArticlePayload>({ title: '', content: '', excerpt: '', images: [] })
const publishForm = reactive({ channel: 'qq' as 'qq' | 'xhs', bot_id: null as number | null, group_openids: [] as string[] })
const filters = reactive({ page: 1, page_size: 15, keyword: '', article_source: 'all', publish_status: 'all' })
async function load() { loading.value = true; try { const result = await articlesApi.list({ page: filters.page, page_size: filters.page_size, keyword: filters.keyword || undefined, article_source: filters.article_source === 'all' ? undefined : filters.article_source as any, publish_status: filters.publish_status === 'all' ? undefined : filters.publish_status as any }); rows.value = result.items; total.value = result.total } catch (e) { message.error(getErrorMessage(e, '无法加载文章')) } finally { loading.value = false } }
function edit(article?: Article) { editing.value = article || null; Object.assign(form, article ? { title: article.title, content: article.content, excerpt: article.excerpt || '', images: [...(article.images || [])] } : { title: '', content: '', excerpt: '', images: [] }); open.value = true }
async function save() { if (!form.title.trim() || !form.content.trim()) return message.warning('请填写标题和正文'); saving.value = true; try { if (editing.value) await articlesApi.update(editing.value.id, { ...form, revision: editing.value.revision }); else await articlesApi.create(form); open.value = false; await load(); message.success('文章已保存') } catch (e) { message.error(getErrorMessage(e, '保存失败')) } finally { saving.value = false } }
async function upload(event: Event) { const files = Array.from((event.target as HTMLInputElement).files || []); (event.target as HTMLInputElement).value = ''; if (!files.length) return; uploading.value = true; try { const result = await articlesApi.upload(files); form.images.push(...result.files.map((item) => item.path)); message.success(`已上传 ${files.length} 张媒体`) } catch (e) { message.error(getErrorMessage(e, '媒体上传失败')) } finally { uploading.value = false } }
function remove(article: Article) { Modal.confirm({ title: `删除「${article.title}」？`, okType: 'danger', okText: '删除', cancelText: '取消', onOk: async () => { await articlesApi.remove(article.id); await load(); message.success('文章已删除') } }) }
async function preparePublish(article: Article) { publishing.value = article; publishForm.channel = 'qq'; publishForm.bot_id = null; publishForm.group_openids = []; try { bots.value = await qqApi.bots(); publishForm.bot_id = bots.value.find((bot) => bot.is_enabled)?.id || null; groups.value = publishForm.bot_id ? await qqApi.joinedGroups(publishForm.bot_id) : []; publishOpen.value = true } catch (e) { message.error(getErrorMessage(e, '读取发布渠道失败')) } }
async function changeBot() { groups.value = publishForm.bot_id ? await qqApi.joinedGroups(publishForm.bot_id) : []; publishForm.group_openids = [] }
async function submitPublish() { if (!publishing.value) return; if (publishForm.channel === 'qq' && (!publishForm.bot_id || !publishForm.group_openids.length)) return message.warning('请选择 QQ 机器人和发送群'); try { await articlesApi.publish(publishing.value.id, { channel: publishForm.channel, bot_id: publishForm.channel === 'qq' ? publishForm.bot_id || undefined : undefined, group_openids: publishForm.channel === 'qq' ? publishForm.group_openids : undefined }); publishOpen.value = false; await load(); message.success('发布任务已提交') } catch (e) { message.error(getErrorMessage(e, '发布失败')) } }
async function showHistory(article: Article) { historyOpen.value = true; try { history.value = (await articlesApi.publishHistory(article.id, { page: 1, page_size: 50 })).items } catch (e) { message.error(getErrorMessage(e, '无法读取发布历史')) } }
onMounted(load); watch(() => [filters.article_source, filters.publish_status], () => { filters.page = 1; void load() })
</script>
<template>
  <div class="page-stack"><PageHeader eyebrow="CONTENT / 02" title="文章管理" description="统一管理 AI 草稿与手动创建的文章"><template #actions><a-button type="primary" @click="edit()"><PlusOutlined /> 新建文章</a-button></template></PageHeader>
    <a-card :bordered="false"><div class="toolbar"><div class="toolbar__controls"><a-input v-model:value="filters.keyword" placeholder="搜索标题或正文" allow-clear style="width:230px" @press-enter="load" /><a-select v-model:value="filters.article_source" style="width:130px" :options="[{label:'全部来源',value:'all'},{label:'AI 生成',value:'ai'},{label:'手动创建',value:'user'}]" /><a-select v-model:value="filters.publish_status" style="width:140px" :options="[{label:'全部状态',value:'all'},{label:'未发布',value:'unpublished'},{label:'已发布',value:'published'},{label:'失败',value:'failed'}]" /></div><span class="toolbar__hint">共 {{ total }} 篇</span></div>
      <a-table :data-source="rows" :loading="loading" row-key="id" :pagination="{current:filters.page,pageSize:filters.page_size,total,showSizeChanger:false}" @change="(page: any) => { filters.page = page.current; void load() }"><a-table-column title="文章"><template #default="{record}"><strong>{{ record.title }}</strong><p class="muted" style="max-width:460px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ record.excerpt || record.content }}</p></template></a-table-column><a-table-column title="来源"><template #default="{record}">{{ record.article_source === 'ai' ? 'AI 生成' : '手动创建' }}</template></a-table-column><a-table-column title="状态"><template #default="{record}"><StatusPill :value="record.publish_status" /></template></a-table-column><a-table-column title="更新时间"><template #default="{record}">{{ formatDateTime(record.updated_at) }}</template></a-table-column><a-table-column title="操作"><template #default="{record}"><a-space><a-button type="link" aria-label="编辑文章" @click="edit(record)"><EditOutlined /></a-button><a-button type="link" aria-label="发布文章" @click="preparePublish(record)"><SendOutlined /></a-button><a-button type="link" aria-label="查看发布历史" @click="showHistory(record)"><HistoryOutlined /></a-button><a-button type="link" danger aria-label="删除文章" @click="remove(record)"><DeleteOutlined /></a-button></a-space></template></a-table-column></a-table>
    </a-card>
    <a-modal v-model:open="open" :title="editing ? '编辑文章' : '新建文章'" ok-text="保存" cancel-text="取消" width="760px" :confirm-loading="saving" @ok="save"><a-form layout="vertical"><a-form-item label="标题" required><a-input v-model:value="form.title" /></a-form-item><a-form-item label="摘要"><a-textarea v-model:value="form.excerpt" :rows="2" /></a-form-item><a-form-item label="正文" required><a-textarea v-model:value="form.content" :rows="14" /></a-form-item><a-form-item label="媒体"><label class="upload-zone"><input type="file" accept="image/*,video/*" multiple @change="upload" /><strong><UploadOutlined /> {{ uploading ? '上传中…' : '上传媒体' }}</strong><span>图片或视频会随文章保存</span></label><div v-if="form.images.length" class="muted" style="margin-top:10px">已添加 {{ form.images.length }} 个媒体文件</div></a-form-item></a-form></a-modal>
    <a-modal v-model:open="publishOpen" title="发布文章" ok-text="提交发布" cancel-text="取消" @ok="submitPublish"><a-form layout="vertical"><a-form-item label="发布渠道"><a-radio-group v-model:value="publishForm.channel"><a-radio value="qq">QQ</a-radio><a-radio value="xhs">小红书</a-radio></a-radio-group></a-form-item><template v-if="publishForm.channel === 'qq'"><a-form-item label="机器人"><a-select v-model:value="publishForm.bot_id" :options="bots.map((bot) => ({label:bot.name,value:bot.id}))" @change="changeBot" /></a-form-item><a-form-item label="发送群"><a-select v-model:value="publishForm.group_openids" mode="multiple" :options="groups.map((group) => ({label:group.name || group.group_openid,value:group.group_openid}))" /></a-form-item></template></a-form></a-modal>
    <a-modal v-model:open="historyOpen" title="发布历史" :footer="null"><a-list :data-source="history"><template #renderItem="{item}"><a-list-item><div><strong>{{ item.channel }}</strong><span class="muted"> · {{ item.target_summary }} · {{ formatDateTime(item.created_at) }}</span></div><StatusPill :value="item.status" /></a-list-item></template></a-list></a-modal>
  </div>
</template>
