<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { ReloadOutlined, ArrowRightOutlined } from '@ant-design/icons-vue'
import { dashboardApi } from '@/services/api'
import { getErrorMessage } from '@/services/http'
import { formatDateTime, formatDuration, formatNumber, formatRelative, tweetTime } from '@/utils/format'
import type { DashboardSummary } from '@/types'
import PageHeader from '@/components/PageHeader.vue'; import MetricCard from '@/components/MetricCard.vue'; import StatusPill from '@/components/StatusPill.vue'
const summary = ref<DashboardSummary | null>(null); const loading = ref(true); const refreshing = ref(false); const error = ref('')
const trend = computed(() => { const values = summary.value?.recent_runs || []; const buckets = new Map<string, { label: string; success: number; failed: number }>(); values.slice().reverse().forEach((run) => { const label = new Date(run.started_at).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); const point = buckets.get(label) || { label, success: 0, failed: 0 }; run.status === 'success' ? point.success++ : point.failed++; buckets.set(label, point) }); return [...buckets.values()].slice(-10) })
async function load(silent = false) { silent ? refreshing.value = true : loading.value = true; error.value = ''; try { summary.value = await dashboardApi.summary() } catch (e) { error.value = getErrorMessage(e, '无法加载仪表盘') } finally { loading.value = false; refreshing.value = false } }
let timer: number | undefined; onMounted(() => { void load(); timer = window.setInterval(() => void load(true), 60_000) }); onBeforeUnmount(() => window.clearInterval(timer))
const serviceRows = computed(() => { const s = summary.value?.server; if (!s) return []; return [{ name: 'API 服务', status: s.api.status, detail: s.api.error || '主进程在线' }, { name: 'PostgreSQL 数据库', status: s.database.status, detail: s.database.latency_ms ? `${s.database.latency_ms} ms` : '连接正常' }, { name: 'Redis 缓存', status: s.redis.status, detail: s.redis.latency_ms ? `${s.redis.latency_ms} ms` : '连接正常' }, { name: '轮询 Worker', status: s.worker.status, detail: s.worker.error || '调度器在线' }] })
</script>

<template><div class="page-stack"><PageHeader eyebrow="OVERVIEW / 01" title="仪表盘" description="监控任务与系统运行概览"><template #actions><a-button :loading="refreshing" @click="load(true)"><ReloadOutlined /> 刷新数据</a-button></template></PageHeader><a-alert v-if="error" class="error-banner" type="error" show-icon :message="error" closable @close="error = ''" /><a-spin :spinning="loading"><template v-if="summary"><div class="metric-grid"><MetricCard label="监听账号" :value="summary.counts.monitored_users" :detail="`${summary.counts.active_users} 个正在运行`" /><MetricCard label="今日新推文" :value="summary.counts.tweets_last_24h" :detail="`累计 ${formatNumber(summary.counts.tweets)}`" accent="slate" /><MetricCard label="今日轮询" :value="summary.polling.runs_last_24h" :detail="`${summary.polling.failed_runs_last_24h} 次失败`" accent="ochre" /><MetricCard label="成功率" :value="`${Number(summary.polling.success_rate).toFixed(1)}%`" detail="过去 24 小时" accent="sage" /></div><div class="two-column"><a-card title="轮询趋势" :bordered="false"><template #extra><span class="card-caption">最近 24 小时</span></template><div class="trend-bars"><div v-for="point in trend" :key="point.label" class="trend-bar"><span :style="{ height: `${Math.max(6, Math.min(100, point.success * 18))}%` }" /><i :style="{ height: `${Math.max(3, Math.min(100, point.failed * 18))}%` }" /><small>{{ point.label }}</small></div><a-empty v-if="!trend.length" description="等待轮询数据" /></div></a-card><a-card title="系统状态" :bordered="false"><div class="list-stack"><div v-for="row in serviceRows" :key="row.name" class="list-row"><div class="list-row__main"><strong>{{ row.name }}</strong><span>{{ row.detail }}</span></div><StatusPill :value="row.status" /></div></div><RouterLink to="/monitoring" class="card-link">查看服务器详情 <ArrowRightOutlined /></RouterLink></a-card></div><div class="two-column"><a-card title="最新采集内容" :bordered="false"><template #extra><RouterLink to="/tweets" class="card-link">查看全部 <ArrowRightOutlined /></RouterLink></template><div v-if="summary.recent_tweets.length" class="list-stack"><div v-for="tweet in summary.recent_tweets.slice(0,5)" :key="tweet.id" class="list-row"><div class="list-row__main"><strong>@{{ tweet.username }}</strong><span>{{ tweet.text }}</span></div><small class="muted">{{ formatRelative(tweetTime(tweet)) }}</small></div></div><a-empty v-else description="还没有采集到推文" /></a-card><a-card title="最近任务" :bordered="false"><div v-if="summary.recent_runs.length" class="list-stack"><div v-for="run in summary.recent_runs.slice(0,6)" :key="run.id" class="list-row"><div class="list-row__main"><strong>@{{ run.username || '未知账号' }}</strong><span>{{ formatDateTime(run.started_at) }} · {{ formatDuration(run.duration_ms) }}</span></div><StatusPill :value="run.status" /></div></div><a-empty v-else description="暂无任务记录" /><RouterLink to="/polling-logs" class="card-link">查看完整记录 <ArrowRightOutlined /></RouterLink></a-card></div></template></a-spin></div></template>
