<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ReloadOutlined } from '@ant-design/icons-vue'; import { message } from 'ant-design-vue'; import { monitoredUsersApi, pollingLogsApi } from '@/services/api'; import { getErrorMessage } from '@/services/http'; import type { MonitoredUser, PollingRun } from '@/types'; import { formatDateTime, formatDuration } from '@/utils/format'; import PageHeader from '@/components/PageHeader.vue'; import StatusPill from '@/components/StatusPill.vue'
const rows = ref<PollingRun[]>([]); const accounts = ref<MonitoredUser[]>([]); const total = ref(0); const loading = ref(false); const filters = reactive({ page:1, page_size:20, monitored_user_id:'', status:'all', trigger:'all', started_after:'', started_before:'' })
async function load() { loading.value = true; try { const result = await pollingLogsApi.list({ page:filters.page, page_size:filters.page_size, monitored_user_id:filters.monitored_user_id || undefined, status:filters.status === 'all' ? undefined : filters.status, trigger:filters.trigger === 'all' ? undefined : filters.trigger, started_after:filters.started_after || undefined, started_before:filters.started_before || undefined }); rows.value = result.items; total.value = result.total } catch (e) { message.error(getErrorMessage(e, '无法加载轮询记录')) } finally { loading.value = false } }
onMounted(async () => { void load(); try { accounts.value = (await monitoredUsersApi.list({ page:1, page_size:100 })).items } catch {} }); watch(() => [filters.monitored_user_id, filters.status, filters.trigger, filters.started_after, filters.started_before], () => { filters.page = 1; void load() })
</script>

<template><div class="page-stack"><PageHeader eyebrow="MONITOR / 03" title="轮询记录" description="追踪每次采集任务的执行结果"><template #actions><a-button @click="load"><ReloadOutlined /> 刷新</a-button></template></PageHeader><a-card :bordered="false"><div class="toolbar"><div class="toolbar__controls"><a-select v-model:value="filters.monitored_user_id" allow-clear placeholder="全部账号" style="width:160px" :options="accounts.map((item) => ({label:`@${item.username}`,value:String(item.id)}))" /><a-select v-model:value="filters.status" style="width:140px" :options="['all','running','success','partial','failed','skipped'].map((value) => ({label:value === 'all' ? '全部状态' : value,value}))" /><a-select v-model:value="filters.trigger" style="width:140px" :options="[{label:'全部来源',value:'all'},{label:'定时',value:'scheduled'},{label:'手动',value:'manual'}]" /><a-input v-model:value="filters.started_after" type="date" /><a-input v-model:value="filters.started_before" type="date" /></div></div><a-table :data-source="rows" :loading="loading" row-key="id" :pagination="{current:filters.page,pageSize:filters.page_size,total,showSizeChanger:false}" @change="(page:any) => { filters.page = page.current; load() }"><a-table-column title="账号"><template #default="{record}"><strong>@{{ record.username || '未知账号' }}</strong><div class="muted">{{ record.trigger || 'scheduled' }}</div></template></a-table-column><a-table-column title="状态"><template #default="{record}"><StatusPill :value="record.status" /></template></a-table-column><a-table-column title="执行时间"><template #default="{record}">{{ formatDateTime(record.started_at) }}</template></a-table-column><a-table-column title="耗时"><template #default="{record}">{{ formatDuration(record.duration_ms) }}</template></a-table-column><a-table-column title="采集 / 新增"><template #default="{record}"><span class="mono">{{ record.tweets_fetched }} / {{ record.tweets_inserted }}</span></template></a-table-column><a-table-column title="错误"><template #default="{record}"><span class="muted">{{ record.error_message || '—' }}</span></template></a-table-column></a-table></a-card></div></template>
