<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Bell, Plus, Trash2 } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import BaseModal from '@/components/BaseModal.vue'
import { qqApi } from '@/services/api'
import type { QQBotAccount, QQJoinedGroup, QQScheduledTask } from '@/types'
import { getErrorMessage } from '@/services/http'
const tasks=ref<QQScheduledTask[]>([]), bots=ref<QQBotAccount[]>([]), groups=ref<QQJoinedGroup[]>([]), open=ref(false), editing=ref<number|null>(null), loading=ref(false)
const form=reactive<any>({name:'',message:'',frequency:'daily',run_time:'09:00',weekdays:[],month_day:1,is_enabled:true,bot_ids:[],groups:[]})
async function load(){ [tasks.value,bots.value]=await Promise.all([qqApi.tasks(),qqApi.bots()]) }
async function chooseBots(){ groups.value=[]; for(const id of form.bot_ids) groups.value.push(...await qqApi.joinedGroups(id)) }
function edit(task?:QQScheduledTask){ editing.value=task?.id??null; Object.assign(form,task?{...task,weekdays:task.weekdays||[],bot_ids:[...task.bot_ids],groups:task.groups.map(g=>({...g}))}:{name:'',message:'',frequency:'daily',run_time:'09:00',weekdays:[],month_day:1,is_enabled:true,bot_ids:[],groups:[]}); open.value=true; if(form.bot_ids.length) chooseBots() }
async function save(){ loading.value=true; try{ const p={name:form.name,message:form.message,frequency:form.frequency,run_time:form.run_time,weekdays:form.weekdays,month_day:form.frequency==='monthly'?form.month_day:null,is_enabled:form.is_enabled,bot_ids:form.bot_ids,groups:form.groups}; editing.value?await qqApi.updateTask(editing.value,p):await qqApi.createTask(p); open.value=false; await load(); ElMessage.success('任务已保存') }catch(e){ElMessage.error(getErrorMessage(e,'保存失败'))}finally{loading.value=false} }
async function remove(task:QQScheduledTask){ await ElMessageBox.confirm('删除后不会再产生新的投递任务，确定删除吗？','删除任务',{type:'warning'}); await qqApi.removeTask(task.id); await load() }
onMounted(load)
</script>
<template><div class="page-stack qq-page"><section class="panel"><header class="data-toolbar"><div><h2>QQ 定时任务</h2><p>定期向多个机器人和群发送固定消息。</p></div><el-button type="primary" @click="edit()"><Plus :size="16"/>新建任务</el-button></header><el-table :data="tasks" stripe><el-table-column label="任务"><template #default="{row}"><strong>{{row.name}}</strong><div class="muted">{{row.message}}</div></template></el-table-column><el-table-column label="计划" width="180"><template #default="{row}">{{row.frequency==='daily'?'每天':row.frequency==='weekly'?'每周':'每月'}} {{row.run_time}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-switch v-model="row.is_enabled" @change="save"/></template></el-table-column><el-table-column label="操作" width="130"><template #default="{row}"><el-button link @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)"><Trash2 :size="14"/></el-button></template></el-table-column></el-table><div v-if="!tasks.length" class="empty"><Bell :size="28"/><p>还没有定时任务</p></div></section><BaseModal :open="open" :title="editing?'编辑 QQ 任务':'新建 QQ 任务'" width="large" @close="open=false"><el-form label-position="top"><el-form-item label="任务名称"><el-input v-model="form.name" maxlength="100"/></el-form-item><el-form-item label="固定消息"><el-input v-model="form.message" type="textarea" :rows="4" maxlength="2000" show-word-limit/></el-form-item><div class="form-grid"><el-form-item label="发送频率"><el-select v-model="form.frequency"><el-option label="每天" value="daily"/><el-option label="每周" value="weekly"/><el-option label="每月" value="monthly"/></el-select></el-form-item><el-form-item label="发送时间"><el-time-picker v-model="form.run_time" format="HH:mm" value-format="HH:mm"/></el-form-item></div><el-form-item v-if="form.frequency==='weekly'" label="每周几"><el-select v-model="form.weekdays" multiple><el-option v-for="d in 7" :key="d" :label="`星期${d}`" :value="d"/></el-select></el-form-item><el-form-item v-if="form.frequency==='monthly'" label="每月几号"><el-input-number v-model="form.month_day" :min="1" :max="31"/></el-form-item><el-form-item label="QQ 机器人"><el-select v-model="form.bot_ids" multiple collapse-tags @change="chooseBots"><el-option v-for="b in bots.filter(x=>x.is_enabled)" :key="b.id" :label="b.name" :value="b.id"/></el-select></el-form-item><el-form-item label="发送群"><el-select v-model="form.groups" multiple value-key="group_openid" collapse-tags><el-option v-for="g in groups" :key="`${g.group_openid}`" :label="g.name||g.group_openid" :value="{bot_id:form.bot_ids[0],group_openid:g.group_openid}"/></el-select></el-form-item><el-switch v-model="form.is_enabled" active-text="启用任务"/></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" :loading="loading" @click="save">保存任务</el-button></template></BaseModal></div></template>
<style scoped>.qq-page{max-width:1200px;margin:auto}.data-toolbar h2{margin:0 0 5px}.data-toolbar p,.muted{color:var(--muted);font-size:12px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.empty{text-align:center;padding:70px;color:var(--muted)}.empty p{margin:10px 0}.qq-page :deep(.el-select),.qq-page :deep(.el-time-picker){width:100%}</style>
