<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { DeleteOutlined, EditOutlined, HistoryOutlined, PlusOutlined } from '@ant-design/icons-vue'
import { message, Modal } from 'ant-design-vue'
import { qqApi } from '@/services/api'
import { getErrorMessage } from '@/services/http'
import type { QQBotAccount, QQScheduledTask } from '@/types'
import { formatDateTime } from '@/utils/format'
import PageHeader from '@/components/PageHeader.vue'; import MetricCard from '@/components/MetricCard.vue'; import StatusPill from '@/components/StatusPill.vue'
type TaskForm = Omit<QQScheduledTask, 'id' | 'last_run_at' | 'next_run_at' | 'created_at' | 'updated_at'>
const tasks = ref<QQScheduledTask[]>([]); const bots = ref<QQBotAccount[]>([]); const loading = ref(false); const open = ref(false); const historyOpen = ref(false); const history = ref<any[]>([]); const editing = ref<QQScheduledTask | null>(null)
const form = reactive<TaskForm>({ name: '', message: '', frequency: 'daily', interval_value: 1, run_time: '09:00:00', weekdays: [], month_day: 1, is_enabled: true, send_immediately: false, bot_ids: [], groups: [] })
const frequencyOptions = [{ label: '每秒', value: 'secondly' }, { label: '每分钟', value: 'minutely' }, { label: '每小时', value: 'hourly' }, { label: '每天', value: 'daily' }, { label: '每周', value: 'weekly' }, { label: '每月', value: 'monthly' }]
const weekdayOptions = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'].map((label, value) => ({ label, value }))
const enabled = computed(() => tasks.value.filter((task) => task.is_enabled).length)
async function load() { loading.value = true; try { [tasks.value, bots.value] = await Promise.all([qqApi.tasks(), qqApi.bots()]) } catch (e) { message.error(getErrorMessage(e, '无法读取 QQ 任务')) } finally { loading.value = false } }
function blank() { Object.assign(form, { name: '', message: '', frequency: 'daily', interval_value: 1, run_time: '09:00:00', weekdays: [], month_day: 1, is_enabled: true, send_immediately: false, bot_ids: [], groups: [] }) }
function edit(task?: QQScheduledTask) { editing.value = task || null; if (task) Object.assign(form, { ...task, bot_ids: [...task.bot_ids], weekdays: [...task.weekdays], groups: task.groups.map((group) => ({ ...group })) }); else blank(); open.value = true }
function addGroup() { form.groups.push({ bot_id: form.bot_ids[0] || bots.value[0]?.id || 0, group_openid: '' }) }
function removeGroup(index: number) { form.groups.splice(index, 1) }
async function save() { if (!form.name.trim() || !form.message.trim() || !form.bot_ids.length || !form.groups.length || form.groups.some((group) => !group.bot_id || !group.group_openid.trim())) return message.warning('请填写任务内容、至少一个机器人和有效群 OpenID'); try { const payload = { ...form, name: form.name.trim(), message: form.message.trim(), groups: form.groups.map((group) => ({ bot_id: Number(group.bot_id), group_openid: group.group_openid.trim() })) }; editing.value ? await qqApi.updateTask(editing.value.id, payload) : await qqApi.createTask(payload); open.value = false; await load(); message.success('任务已保存') } catch (e) { message.error(getErrorMessage(e, '保存任务失败')) } }
async function toggle(task: QQScheduledTask) { try { await qqApi.updateTask(task.id, { ...task, is_enabled: !task.is_enabled, send_immediately: false }); await load() } catch (e) { message.error(getErrorMessage(e, '更新任务失败')) } }
function remove(task: QQScheduledTask) { Modal.confirm({ title: `删除任务「${task.name}」？`, okType: 'danger', okText: '删除', cancelText: '取消', onOk: async () => { await qqApi.removeTask(task.id); await load(); message.success('任务已删除') } }) }
async function showHistory(task: QQScheduledTask) { historyOpen.value = true; try { history.value = (await qqApi.deliveries({ task_id: task.id, page: 1, page_size: 100 })).items } catch (e) { message.error(getErrorMessage(e, '读取历史失败')) } }
onMounted(load)
</script>
<template>
  <div class="page-stack"><PageHeader eyebrow="CHANNEL / 03" title="QQ 任务" description="配置定时消息任务和投递范围"><template #actions><a-button type="primary" @click="edit()"><PlusOutlined /> 新建任务</a-button></template></PageHeader><div class="metric-grid"><MetricCard label="任务总数" :value="tasks.length" detail="全部计划" /><MetricCard label="运行中" :value="enabled" detail="已启用计划" accent="sage" /></div>
    <a-card :bordered="false"><a-table :data-source="tasks" :loading="loading" row-key="id" :pagination="false"><a-table-column title="任务"><template #default="{record}"><strong>{{ record.name }}</strong><div class="muted">{{ record.message }}</div></template></a-table-column><a-table-column title="计划"><template #default="{record}">{{ record.frequency }} · {{ record.run_time }}</template></a-table-column><a-table-column title="状态"><template #default="{record}"><StatusPill :value="record.is_enabled" /></template></a-table-column><a-table-column title="下次执行"><template #default="{record}">{{ formatDateTime(record.next_run_at) }}</template></a-table-column><a-table-column title="操作"><template #default="{record}"><a-space><a-switch size="small" :checked="record.is_enabled" @change="toggle(record)" /><a-button type="link" aria-label="编辑任务" @click="edit(record)"><EditOutlined /></a-button><a-button type="link" aria-label="查看任务历史" @click="showHistory(record)"><HistoryOutlined /></a-button><a-button type="link" danger aria-label="删除任务" @click="remove(record)"><DeleteOutlined /></a-button></a-space></template></a-table-column></a-table></a-card>
    <a-modal v-model:open="open" :title="editing ? '编辑 QQ 任务' : '新建 QQ 任务'" ok-text="保存" cancel-text="取消" width="720px" @ok="save"><a-form layout="vertical"><div class="form-grid"><a-form-item label="任务名称"><a-input v-model:value="form.name" /></a-form-item><a-form-item label="启用"><a-switch v-model:checked="form.is_enabled" /></a-form-item></div><a-form-item label="消息内容"><a-textarea v-model:value="form.message" :rows="4" /></a-form-item><div class="form-grid"><a-form-item label="发送频率"><a-select v-model:value="form.frequency" :options="frequencyOptions" /></a-form-item><a-form-item label="间隔"><a-input-number v-model:value="form.interval_value" :min="1" :max="365" style="width:100%" /></a-form-item></div><div class="form-grid"><a-form-item label="执行时间"><a-input v-model:value="form.run_time" placeholder="09:00:00" /></a-form-item><a-form-item v-if="form.frequency === 'monthly'" label="每月日期"><a-input-number v-model:value="form.month_day" :min="1" :max="31" style="width:100%" /></a-form-item></div><a-form-item v-if="form.frequency === 'weekly'" label="每周执行日"><a-checkbox-group v-model:value="form.weekdays" :options="weekdayOptions" /></a-form-item><a-form-item label="机器人"><a-select v-model:value="form.bot_ids" mode="multiple" :options="bots.filter((bot) => bot.is_enabled).map((bot) => ({ label: bot.name, value: bot.id }))" /></a-form-item><a-form-item label="发送群"><div v-for="(group, index) in form.groups" :key="index" class="group-editor"><a-select v-model:value="group.bot_id" :options="bots.filter((bot) => form.bot_ids.includes(bot.id)).map((bot) => ({ label: bot.name, value: bot.id }))" placeholder="机器人" /><a-input v-model:value="group.group_openid" placeholder="群 OpenID" /><a-button type="link" danger @click="removeGroup(index)"><DeleteOutlined /></a-button></div><a-button type="dashed" block @click="addGroup">添加发送群</a-button></a-form-item></a-form></a-modal>
    <a-modal v-model:open="historyOpen" title="投递历史" :footer="null"><a-list :data-source="history"><template #renderItem="{item}"><a-list-item><span>{{ item.target_name || item.target_summary }}</span><StatusPill :value="item.status" /></a-list-item></template></a-list></a-modal>
  </div>
</template>
