<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { ReloadOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { systemApi } from '@/services/api'; import { getErrorMessage } from '@/services/http'; import { formatBytes, formatDateTime } from '@/utils/format'; import type { SystemMetrics } from '@/types'
import PageHeader from '@/components/PageHeader.vue'; import StatusPill from '@/components/StatusPill.vue'; import MetricCard from '@/components/MetricCard.vue'
const metrics = ref<SystemMetrics | null>(null); const loading = ref(true); const refreshing = ref(false); const error = ref('')
const services = computed(() => { const s = metrics.value; if (!s) return []; return [{ name: 'API 服务', value: s.api }, { name: 'PostgreSQL 数据库', value: s.database }, { name: 'Redis 缓存', value: s.redis }, { name: '轮询 Worker', value: s.worker }, ...(s.ai_worker ? [{ name: 'AI Worker', value: s.ai_worker }] : []), ...(s.qq_worker ? [{ name: 'QQ Worker', value: s.qq_worker }] : []), ...(s.xhs_worker ? [{ name: '小红书 Worker', value: s.xhs_worker }] : [])] })
async function refresh(show = false) { refreshing.value = true; try { metrics.value = await systemApi.metrics() } catch (e) { error.value = getErrorMessage(e, '无法读取服务器指标'); if (show) message.error(error.value) } finally { loading.value = false; refreshing.value = false } }
let timer: number | undefined; onMounted(() => { void refresh(); timer = window.setInterval(() => void refresh(), 10_000) }); onBeforeUnmount(() => window.clearInterval(timer))
</script>

<template><div class="page-stack"><PageHeader eyebrow="SYSTEM / 01" title="运行监控" description="查看服务器资源、服务健康与 Worker 运行状态"><template #actions><a-button :loading="refreshing" @click="refresh(true)"><ReloadOutlined /> 立即刷新</a-button></template></PageHeader><a-alert v-if="error" class="error-banner" type="warning" :message="error" show-icon /><a-spin :spinning="loading"><template v-if="metrics"><div class="metric-grid"><MetricCard label="CPU 使用率" :value="`${metrics.cpu_percent.toFixed(1)}%`" :detail="metrics.load_average ? `负载 ${metrics.load_average.map((n) => n.toFixed(2)).join(' / ')}` : '系统使用率'" /><MetricCard label="内存" :value="`${metrics.memory.percent.toFixed(1)}%`" :detail="`${formatBytes(metrics.memory.used_bytes)} / ${formatBytes(metrics.memory.total_bytes)}`" accent="slate" /><MetricCard label="磁盘" :value="`${metrics.disk.percent.toFixed(1)}%`" :detail="`${formatBytes(metrics.disk.used_bytes)} / ${formatBytes(metrics.disk.total_bytes)}`" accent="ochre" /><MetricCard label="运行时间" :value="`${Math.floor(metrics.uptime_seconds / 3600)}h`" :detail="`采集于 ${formatDateTime(metrics.generated_at)}`" accent="sage" /></div><a-card title="服务健康" :bordered="false"><a-table :data-source="services" :pagination="false" row-key="name"><a-table-column title="服务" data-index="name" /><a-table-column title="状态"><template #default="{ record }"><StatusPill :value="record.value.status" /></template></a-table-column><a-table-column title="CPU / 内存"><template #default="{ record }">{{ record.value.cpu_percent != null ? `${Number(record.value.cpu_percent).toFixed(1)}%` : '—' }} / {{ record.value.memory_used_bytes != null ? formatBytes(Number(record.value.memory_used_bytes)) : '—' }}</template></a-table-column><a-table-column title="说明"><template #default="{ record }"><span class="muted">{{ record.value.error || (record.value.latency_ms ? `${record.value.latency_ms} ms` : '运行正常') }}</span></template></a-table-column></a-table></a-card></template></a-spin></div></template>
