<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { BookOpen, CheckCircle2, Send, ShieldCheck, UploadCloud } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { xhsApi } from '@/services/api'
import { getErrorMessage } from '@/services/http'
const loading = ref(false); const status = ref<any>(null)
const form = reactive({ cookie: '', title: '', content: '', images: '' })
async function refresh() { try { status.value = await xhsApi.status() } catch (e) { ElMessage.error(getErrorMessage(e)) } }
async function login() { if (!form.cookie.trim()) return ElMessage.warning('请输入 Cookie'); loading.value = true; try { await xhsApi.login(form.cookie); form.cookie = ''; await refresh(); ElMessage.success('登录态已保存') } catch (e) { ElMessage.error(getErrorMessage(e)) } finally { loading.value = false } }
async function publish() { if (!form.title || !form.content || !form.images.trim()) return ElMessage.warning('请填写标题、正文和图片路径'); loading.value = true; try { await xhsApi.post({ title: form.title, content: form.content, images: form.images.split('\n').map(x => x.trim()).filter(Boolean) }); ElMessage.success('发布成功') } catch (e) { ElMessage.error(getErrorMessage(e, '发布失败')) } finally { loading.value = false } }
onMounted(refresh)
</script>
<template><div class="xhs-page page-stack"><header class="xhs-hero"><div class="xhs-hero__mark"><BookOpen :size="22" /></div><div><span class="xhs-kicker">CONTENT CHANNEL</span><h1>小红书管理</h1><p>从登录态到图文发布，集中管理你的内容出口。</p></div><div class="xhs-status" :class="{ 'is-connected': status?.connected }"><span></span>{{ status?.connected ? '账号已连接' : '等待连接' }}</div></header><div class="xhs-grid"><section class="panel xhs-card"><div class="xhs-card__head"><div><span class="xhs-index">01</span><h2>连接账号</h2><p>使用 Cookie 建立 xhs-cli 登录态</p></div><ShieldCheck :size="22" /></div><label>小红书 Cookie</label><el-input v-model="form.cookie" type="password" show-password placeholder="a1=...; web_session=..." /><small>凭据仅交给后端 CLI 使用，不会显示在页面或日志中。</small><el-button type="primary" :loading="loading" @click="login"><CheckCircle2 :size="16" />保存登录态</el-button></section><section class="panel xhs-card"><div class="xhs-card__head"><div><span class="xhs-index">02</span><h2>发布图文</h2><p>准备好内容后，一次发布到小红书</p></div><UploadCloud :size="22" /></div><label>标题</label><el-input v-model="form.title" maxlength="80" show-word-limit placeholder="写一个清晰、有记忆点的标题" /><label>正文</label><el-input v-model="form.content" type="textarea" :rows="7" placeholder="分享你的观点、步骤或体验" /><label>图片路径</label><el-input v-model="form.images" type="textarea" :rows="3" placeholder="每行一张图片的绝对路径" /><div class="xhs-compose__foot"><span>{{ form.images.split('\n').filter(Boolean).length }} 张图片</span><el-button type="primary" :loading="loading" @click="publish"><Send :size="16" />发布笔记</el-button></div></section></div></div></template>
