<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { BookOpen, CheckCircle2, Send, ShieldCheck, UploadCloud } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { xhsApi } from '@/services/api'
import { getErrorMessage } from '@/services/http'
const loading=ref(false), status=ref<any>(null), preview=ref<string | null>(null); const form=reactive({a1:'',web_session:'',title:'',content:'',images:[] as string[],previews:[] as string[]})
async function refresh(){try{status.value=await xhsApi.status()}catch(e){ElMessage.error(getErrorMessage(e))}}
async function login(){if(!form.a1||!form.web_session)return ElMessage.warning('请填写 a1 和 web_session');loading.value=true;try{await xhsApi.login({a1:form.a1,web_session:form.web_session});form.a1='';form.web_session='';await refresh();ElMessage.success('登录态已保存')}catch(e){ElMessage.error(getErrorMessage(e))}finally{loading.value=false}}
async function chooseFiles(e:Event){const files=Array.from((e.target as HTMLInputElement).files||[]);if(!files.length)return;loading.value=true;try{const r:any=await xhsApi.upload(files);form.images.push(...r.files.map((x:any)=>x.path));form.previews.push(...files.map(file=>URL.createObjectURL(file)));ElMessage.success(`已上传 ${files.length} 张图片`)}catch(e){ElMessage.error(getErrorMessage(e,'上传失败'))}finally{loading.value=false}}
function removeImage(index:number){const url=form.previews[index];if(url) URL.revokeObjectURL(url);form.images.splice(index,1);form.previews.splice(index,1)}
async function publish(){if(!form.title||!form.content||!form.images.length)return ElMessage.warning('请填写标题、正文并上传图片');loading.value=true;try{await xhsApi.post({title:form.title,content:form.content,images:form.images});ElMessage.success('发布成功')}catch(e){ElMessage.error(getErrorMessage(e,'发布失败'))}finally{loading.value=false}}
onMounted(refresh)
</script>
<template><div class="xhs-page page-stack"><header class="xhs-hero"><div class="xhs-hero__mark"><BookOpen :size="22"/></div><div><span class="xhs-kicker">CONTENT CHANNEL</span><h1>小红书管理</h1><p>从登录态到图文发布，集中管理你的内容出口。</p></div><div class="xhs-status" :class="{'is-connected':status?.connected}"><span/>{{status?.connected?'账号已连接':'等待连接'}}</div></header><div class="xhs-grid"><section class="panel xhs-card"><div class="xhs-card__head"><div><span class="xhs-index">01</span><h2>连接账号</h2><p>分开填写浏览器 Cookie 字段</p></div><ShieldCheck :size="22"/></div><div class="xhs-guide"><strong>操作教程</strong><ol><li>在浏览器登录小红书。</li><li>打开开发者工具的 Application / Storage。</li><li>进入小红书域名 Cookies，复制 a1 和 web_session 的值。</li><li>分别粘贴并保存，系统会验证登录态。</li></ol></div><label>a1</label><el-input v-model="form.a1" type="password" show-password :placeholder="status?.connected?'已保存，输入新值可更新':'请输入 a1 Cookie 值'"/><label>web_session</label><el-input v-model="form.web_session" type="password" show-password :placeholder="status?.connected?'已保存，输入新值可更新':'请输入 web_session Cookie 值'"/><small>已保存的值不会回显，凭据只在后端 CLI 调用时使用。</small><el-button type="primary" :loading="loading" @click="login"><CheckCircle2 :size="16"/>保存登录态</el-button></section><section class="panel xhs-card"><div class="xhs-card__head"><div><span class="xhs-index">02</span><h2>发布图文</h2><p>上传图片后发布到小红书</p></div><UploadCloud :size="22"/></div><label>标题</label><el-input v-model="form.title" maxlength="80" show-word-limit placeholder="写一个清晰、有记忆点的标题"/><label>正文</label><el-input v-model="form.content" type="textarea" :rows="7" placeholder="分享你的观点、步骤或体验"/><label>照片</label><label class="xhs-upload-zone"><input class="xhs-file-input" type="file" accept="image/jpeg,image/png,image/webp" multiple @change="chooseFiles"/><UploadCloud :size="20"/><strong>选择照片</strong><span>支持 JPG、PNG、WebP，可多选</span></label><div v-if="form.previews.length" class="xhs-photo-grid"><div v-for="(photo,index) in form.previews" :key="photo" class="xhs-photo"><button type="button" @click.stop="removeImage(index)">×</button><img :src="photo" alt="已上传照片" @click="preview=photo"/></div></div><div class="xhs-compose__foot"><span>{{form.images.length}} 张图片已上传</span><el-button type="primary" :loading="loading" @click="publish"><Send :size="16"/>发布笔记</el-button></div></section></div></div></template>
